name: cubancigarinc.com/contactus
favicon: null
layout_spectrum: 0.18406817084178329
typography_spectrum: 0.6183517375029624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1091174460016191
  lightness: 0.04178226855583489
  saturation: 0.45013991836458445
  rhythmicContrast: 0.3152954769320786
purpose: []
